//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.14
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub a2321714-63f6-4541-8be7-bd240a45cef0 aws-my-sample-app-android-v0.14";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:6f77aad0-1c62-41d5-bc9d-933c3739c6cd";
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_eqzrmf5J6";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "5ffihmb6snkg2nvc483q1ppelo";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "15b4fval51r9kf8n989rbjbu0lf6tvl1e6skdd43f2l23ukhmlqj";
}
